### ISSUE TITLE
Error while running process

### ISSUE THREAD

**Issue by fsasvari** [asahasrabuddhe/laravel-mjml#3]
Hi there, I have an error in file `src\Process\MJML.php` on line **45**:

    43     if (! $this->process->isSuccessful()) {
    44         throw new ProcessFailedException($this->process);
    45     }

And the following error occurs:
Output: ================ Command line error: Error Output: ================ File: C:/xampp/htdocs/projects/project/storage/framework/views/261d91e357c4a5c640dcaba6375f5a729de8a6b6.php TypeError: Cannot set property 'content' of null Input file(s) failed to render openssl config failed: error:02001002:system library:fopen:No such file or directory

Have any idea whats wrong ?

**Comment by fsasvari** [comment]
Figured it out! I places basic HTML tags and MJML can't process it. When i places `<mjml>` tags, everything was OK.

But now, there is other problems:
1. Problem with sending email more then once. Second time it strips part of HTML
2. Plain text mail doesn't get saved and sent

I was using Mailtrap.io to test mail sending.

**Comment by asahasrabuddhe** [comment]
@fsasvari Thanks for this. I will look into this and get back to you.

**Comment by asahasrabuddhe** [comment]
Hello @fsasvari ,

I am finally able to get back to you on the issues you reported.

1. This issue is now fixed. This was happening due to the package trying to re-compile views.
2. Now the package attempts to generate plain text version of the HTML email. Please let me know if this is suitable or I am open to suggestions on how this can be achieved.
3. I am thinking over a way of better implementing this or atleast specifying something in the documentation so people are not confused. More on this later.
4. Can you please elaborate on this? I have not faced this before and would gladly help you out on this.

Regards,
Ajitem

**Comment by fsasvari** [comment]
Hi @asahasrabuddhe,

1. Working now, thx
2. The generate process of plain text version is OK, but can you use LaravelMail's built in text() method ?

```
return $this
    ->to($config->get('mail.from.address'), $config->get('mail.from.name'))
    ->subject($lang->get('web/email.contact.subject'))
    ->mjml('emails.emails.contact', ['input' => $this->input]) // need to set "input" array here, based on 4th question
    ->text('emails.plains.contact');
```

3. Problem with MJML include, does not work (or maybe my implementation is not good):

```
<mj-include path='../includes/header' />
```

4. Problem with setting public variables ($input array is not provided in blade):

```
/**
 * Create a new message instance.
 *
 * @param  array  $input
 * @return void
 */
public function __construct(array $input = [])
{
    $this->input = $input;
}
```

**Comment by fsasvari** [comment]
3. Blade "include" works!

`@include('emails.includes.header') // works fine, don't need to use <mj-include />`
